GET http://127.0.0.1:8000/v1/playlist-artists?url=https://music.yandex.ru/users/kondrenkokp/playlists/3
Accept: application/json

###

GET http://127.0.0.1:8000/v1/playlist-artists?url=https://music.yandex.ru/users/kondrenkokp/playlists/3&url=https://music.yandex.ru/users/kondrenkokp/playlists/1276
Accept: application/json

###

GET http://127.0.0.1:8000/v1/artist-concerts?id=6826935
Accept: application/json

###

GET http://127.0.0.1:8000/v1/artist-concerts?id=6826935&id=6761875
Accept: application/json

###
